main: com.massivecraft.bitechance.BiteChance
name: BiteChance
version: 0.0.1
website: http://massivecraft.com/
authors: [yendor46]
description: BiteChance buffs the fishing bite chance proportional to the mcMMO fishing level, with a maximum of 80%.  
depend: [mcMMO, mcore]
softdepend: []
commands:
  bitechance:
    description: Shows your fishing bite chance